[config]
schemaVersion = "0.0.1"

[package]
namespace = "www_Day_Dream"
name = "Shuv"
description = "A Client-Side mod that lets you shove your friends."
websiteUrl = "https://github.com/wwwDayDream/Shuv"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
CommanderCat101-ContentSettings = "1.0.1"

[build]
icon = "icon.png"
readme = "README.TS.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../Shuv/bin/Release/netstandard2.1/Shuv.dll"
target = "/BepInEx/plugins/Shuv/"

[publish]
communities = [ "content-warning" ]
repository = "https://thunderstore.io"

# "bepinex", "clientside" 
[publish.categories]
content-warning = [ "mods", "misc" ] 
